all: pull-phil

pull-phil:
	git clone https://github.com/wiesel78/wiesels-vim.git ${HOME}/.vim
	ln -s ${HOME}/.vim/vimrc ${HOME}/.vimrc


pull-henrik:
	curl -o - https://raw.githubusercontent.com/begriffs/haskell-vim-now/master/install.sh | bash
