#!/usr/bin/perl -w
use v5.16;

my $interface 	= (shift (@_) or "wlan0");
my @iwlist = iwlistscan();


sub iwlistscan {
	my $interface 	= (shift (@_) or "wlan0");
	my @iwlist 		= `iwlist $interface scan`;
	return @iwlist;
}

sub getssids {
	my @ssids;
	
	foreach (@_){
		if ( /.*ESSID[:]\"(.*)\"/ ){
			push @ssids, $1;
		}
	}
	
	return @ssids;
}

sub getNetworkList {
	my @zellen = ();
	my $ref = 0;
	
	foreach (@_){
		if ( /\s*Cell\s*(\d*)\s*-/ ){
			my %network;			
			$ref = \%network;
			push @zellen, $ref;
		}
		
		if( /\sAddress:\s*(.*)/ ){
			${$ref}{'address'} = $1;
		}elsif( /\sChannel:(.*)/ ){
			${$ref}{'channel'} = $1;
		}elsif( /\sFrequency:(\d\.*\d*\s*[a-zA-Z]*)/ ){
			${$ref}{'frequency'} = $1;
		}elsif( /\sEncryption\skey:(.*)/ ){
			${$ref}{'encryption_key'} = $1;
		}elsif( /\sESSID:"(.*)"/ ){
			${$ref}{'essid'} = $1;
		}elsif( /\sQuality=(\d*)\/(\d*).*/ ){
			${$ref}{'quality'} = "$1/$2";
		}elsif( /\sGroup Cipher\s:\s(.*)/ ){
			${$ref}{'group'} = $1;
		}elsif( /\sPairwise\sCiphers\s\(*\d*\)*\s:\s(.*)/ ){
			${$ref}{'pairwise'} = $1;
		}elsif( /\sAuthentication\sSuites\s\(*\d*\)*\s:\s(.*)/ ){
			${$ref}{'authentication_suites'} = $1;
		}elsif( /\sIE:\sIEEE\s(.*)\/(.*)/ ){
			${$ref}{'wpa'} = $2;
		}
		
	}
	
	return @zellen;
}


foreach (getNetworkList(@iwlist)){
	say ${$_}{'essid'};
}
