awesome-sync-to-client: awesome/rc.lua
	mkdir -p ${HOME}/.config/awesome
	cp awesome/rc.lua ${HOME}/.config/awesome/rc.lua
	cp awesome/theme.lua ${HOME}/.config/awesome/theme.lua
	cp awesome/wallpaper.jpg ${HOME}/.config/awesome/wallpaper.jpg
