awesome-sync-to-client: rc.lua
	mkdir -p ${HOME}/.config/awesome
	cp rc.lua ${HOME}/.config/awesome/rc.lua
	cp theme.lua ${HOME}/.config/awesome/theme.lua
	cp wallpaper.jpg ${HOME}/.config/awesome/wallpaper.jpg
