#!/bin/bash
#####################################################
#													#
# This scripts follows after arch-chroot 			#
# from "arch-install".								#
# It configures the basic installation 				#
# for a german system and the linuc-ck-corex kernel #
#####################################################

pacmanconf () {
	# adding important repos
	nano /etc/pacman.conf
	echo "[archlinuxfr]" >> /etc/pacman.conf
	echo "Server = http://repo.archlinux.fr/\$arch" >> /etc/pacman.conf
	echo "" >> /etc/pacman.conf
	echo "[repo-ck]" >> /etc/pacman.conf
	echo "SigLevel = PackageRequired" >> /etc/pacman.conf
	echo "Server = http://repo-ck.com/\$arch" >> /etc/pacman.conf
}

konfiguration () {
	# basic configuration for a german system
	read -p "Hostname" HOST
	echo ${HOST} > /etc/hostname
	echo LANG=de_DE.UTF-8 > /etc/locale.conf
	echo LC_COLLATE=C >> /etc/locale.conf
	echo KEYMAP=de-latin1 > /etc/vconsole.conf
	ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
	echo "#<ip-address>	<hostname.domain.org>	<hostname>" > /etc/hosts
	echo "127.0.0.1	localhost.localdomain	localhost $HOST" >> /etc/hosts
	echo "::1		localhost.localdomain	localhost $HOST" >> /etc/hosts
	# adding modules for btrfs and btrfs-subvolumes in mkinit
	sed -i 's/MODULES=""/MODULES="crc32c"/' /etc/mkinitcpio.conf
	sed -i '/HOOKS/s/sata/sata btrfs/' /etc/mkinitcpio.conf
	sed -i '/HOOKS/s/fsck//' /etc/mkinitcpio.conf
	sed -i 's/#de_DE.UTF-8/de_DE.UTF-8/' /etc/locale.gen
	sed -i 's/#de_DE/de_DE/' /etc/locale.gen
	sed -i 's/#de_DE@euro/de_DE@euro/' /etc/locale.gen
	locale-gen
	
	# installing some services and adding them to systemd and also corex-kernel
	pacmanconf
	pacman -Syu --noconfirm linux-ck-corex linux-ck-corex-headers acpid ntp dbus avahi cups
	mkinitcpio -p linux
	mkinitcpio -p linux-ck
	chsh -S /bin/zsh
	systemctl enable acpid.service
	systemctl enable ntpd.service
	systemctl enable avahi-daemon.service
	systemctl enable cups.service
	ntp -gq
	hwclock -w
	
	bios
	# adding user and setting root
	echo "Rootpasswort"
	passwd
	echo "Userkonfiguration"
	adduser
	
	echo "Leaving arch-chroot"
	sleep 3
	exit
}

bios() {
	# grub-install on boot hdd
	read -p "Bootpartition eingeben: " BOOT_HDD
	pacman -S --noconfirm grub-bios
	grub-mkconfig -o /boot/grub/grub.cfg
	grub-install ${BOOT_HDD}
	
	unset BOOT_HDD
}

konfiguration
