#!/bin/bash
#
# Installskript für Arch-Linux mit Systemd, Btrfs, Linux-ck
# 
# Es wird empfohlen sich das Skript vorher anzuschauen und bei
# bedarf anzupassen, besonders wenn andere Filesysteme erwünscht sind
# Bei Grub ist elevater=bfq nachzutragen
#

partitionierung() {
	# Sprache auf deutsch stellen und HDDs abfragen
	loadkeys de			
	read -p "zu formatierende Platte angeben: " BOOT_HDD
	gdisk ${BOOT_HDD}
	read -p "Platten für btrfs eingeben: " BTRFS_HDD
	read -p "zusätzliche Optionen (-L schon vergeben): " BTRFS_OPT
	read -p "Swap angeben: " SWAP 

	# HDDs formatieren und mounten 
	mkswap -L swap ${SWAP}
	mkfs.btrfs ${BTRFS_OPT} -L btrfs-root ${BTRFS_HDD}
	sleep 5
	mount -o compress /dev/disk/by-label/btrfs-root /mnt
	swapon -L swap
	
	# Subvolumes unter Btrfs erstellen
	VOLUME_COUNT=0
	NEW_SUBVOL=true
	while ( ${NEW_SUBVOL} -eq "true" )
	do
		read -p "Name des Subvol: " SUBVOL[${VOLUME_COUNT}]
		btrfs subvolume create /mnt/${SUBVOL[${VOLUME_COUNT}]}
		read -p "Weitere Subvols? [y/n]: " EINGABE
		if [ ${EINGABE} = "y" ] 
			then
				((VOLUME_COUNT++))
			else
				NEW_SUBVOL=false
			fi
	done
	sleep 3
	umount /mnt
	
	# Subvolumes mounten
	MOUNT_COUNT=0
	while (( ${MOUNT_COUNT} <= ${VOLUME_COUNT} )) 
	do
		read -p "Einhängepunkt für ${SUBVOL[${MOUNT_COUNT}]} ab /mnt: " MOUNTPOINT
		if [ ! -d /mnt/${MOUNTPOINT} ]
			then 
				mkdir /mnt/${MOUNTPOINT}
		fi
		mount -o compress,subvol=${SUBVOL[${MOUNT_COUNT}]} /dev/disk/by-label/btrfs-root /mnt/${MOUNTPOINT} 
		((MOUNT_COUNT++))
	done
	
	# Variablen löschen; eigentlich überflüssig, aber der Eindeutigkeit halber
	unset BOOT_HDD MOUNT_COUNT NEW_SUBVOL VOLUME_COUNT EINGABE SWAP BTRFS_HDD BTRFS_OPT
}

installation () {
	# Wlan bei Bedarf aktivieren
	read -p "Wlan aktivieren? [y/n]: " WLAN
	if [ ${WLAN} = "y" ] 
		then
			wlan
	fi
	
	# Basisinstallation und fstab generieren
	sed -i 's/#Server/Server/' /etc/pacman.d/mirrorlist
	sleep 5
	pacstrap /mnt base base-devel btrfs-progs zsh grml-zsh-config
	genfstab -Lp /mnt >> /mnt/etc/fstab

	unset WLAN
	cp ./after-chroot /mnt/tmp/
	arch-chroot /mnt /tmp/after-chroot
	
	# Umount; Abschluss der Grundinstallation
	umount --all
	
}

wlan () {
	cp /etc/network.d/examples/wireless-wpa /etc/network.d/
	#read -p "Netzwerkname: " WPANAME
	#read -p "Netzwerkkey: " WPAKEY
	nano /etc/network.d/wireless-wpa
	netcfg wireless-wpa
}

echo "1 - Partitionierung"
echo "2 - Installation"
echo "3 - 1 + 2"
read -p "Option eingeben [1|2|3]:" OPT

case ${OPT} in
	1) partitionierung;;
	2) installation;;
	3) konfiguration;;
	4) partitionierung
	   installation;;
	*) echo "Benutzung:[1|2|3]"
	   echo	"1 - Partitionierung"
	   echo "2 - Installation"
	   echo "3 - 1 + 2"
esac
