all: administration entwicklung dateisystem vm drucker gnome internet netzwerk multimedia treiber xorg 

administration : 
	pacman -S rxvt-unicode lshw gdisk rsync arch-install-scripts vim numlockx 

entwicklung : 
	pacman -S git geany gedit openmpi jre7-openjdk eclipse 

dateisystem : 
	pacman -S ntfsprogs ntfs-3g dosfstools libdvdread libdvdcss libdvdnav 

vm : 
	pacman -S qemu   

drucker : 
	pacman -S cups hplip 

gnome : 
	pacman -S gnome transmission-gtk file-roller 

internet : 
	pacman -S ntp chromium ddclient telepathy-gabble flashplugin freetalk 

netzwerk : 
	pacman -S networkmanager network-manager-applet networkmanager-openvpn networkmanager-pptp avahi nss-mdns nfs-utils  nmap nbd samba smbclient gvfs-smb 

multimedia : 
	pacman -S vlc clementine gimp p7zip libreoffice gstreamer0.10 gstreamer0.10-bad gstreamer0.10-bad-plugins gstreamer0.10-ffmpeg gstreamer0.10-good gstreamer0.10-good-plugins gstreamer0.10-ugly gstreamer0.10-ugly-plugins blender pitivi 

treiber : 
	pacman -S alsa-lib alsa-utils xf86-video-nouveau nouveau-dri xf86-input-synaptics 

xorg : 
	pacman -S xorg-server xorg-server-utils xorg-utils xorg-xinit 
