CONFIG=${HOME}/.emacs.d/

all:

pull-henrik:
	cp _henrik/ ${CONFIG}

push-henrik:
	cp ${CONFIG}/init.el ./_henrik/

#from-client:
#	if [ -d $(CONFIG)/ ]; then \
#	cp $(CONFIG)/prelude-modules.el ./prelude-modules.el; \
#	cp -r $(CONFIG)/personal/ ./; \
#	fi

#to-client:
#	mkdir -p $(CONFIG)
#	cp ./prelude-modules.el $(CONFIG)prelude-modules.el
#	cp -r ./personal/ $(CONFIG)

#fresh-client:
##	./deploy.sh
